version: "3.6"

services:
  web:
    image: node:18
    volumes:
      - ./web:/opt/web
    working_dir: /opt/web
    ports:
      - 3000:3000
    depends_on:
      - api
    command: npm run dev

  api:
    image: golang
    volumes:
      - ./api:/opt/api
    working_dir: /opt/api
    command: go run main.go