name: Deploy to ghcr.io

on:
  push:
    branches:
      - master
    paths:
      - web/**

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ACCESS_TOKEN }}

      - name: Create dot env file
      - shell: bash
        run: |
          touch web/.env
          echo "NEXT_PUBLIC_API_ENDPOINT=${{ secrets.NEXT_PUBLIC_API_ENDPOINT }}" >> web/.env
          echo "NEXT_PUBLIC_STORAGE=${{ secrets.NEXT_PUBLIC_STORAGE }}" >> web/.env

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./web
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/privateserver-web:latest
            ghcr.io/${{ github.repository_owner }}/privateserver-web:1.0.0
