name: Deploy to ghcr.io

on:
  push:
    branches:
      - master
    paths:
      - api/**

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ACCESS_TOKEN }}

      - name: generate .env
        run: chmod +x set-up-env.test.sh && sh set-up-env.test.sh
        env:
          HOST: ${{ secrets.HOST }}
          HOST_USER: ${{ secrets.HOST_USER }}
          HOST_PORT: ${{ secrets.HOST_PORT }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./api
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/privateserver-api:latest
            ghcr.io/${{ github.repository_owner }}/privateserver-api:1.0.0
